# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c604e9123eb3f5326a80826052128e91a660f818f4a5a5661c46c3563c1650b4323e6a83a26d0771ebcdb71573333c7b2d5287d6004f474496de0eedf13489ff

test:
  secret_key_base: 3459d2543695870fd3640dc0cb1a583cf9e5178749cf943ab6210c57d499d0a1656dd598d512ddd0b2c4bce0633d318d7992acb5f744eee764eab32864a83083

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
